### ISSUE TITLE
grunt watch fails

### ISSUE THREAD

**Issue by augster** [tridium/grunt-init-niagara#6]
Running grunt watch fails. I get the following errors from PhantomJS. I get the same error when running grunt ci.

`Running "watchForChange" task
Waiting...
>> File "src\rc\BsModuleWidget.js" changed.

Running "runWatchTasks" task

Running "babel:watch" (babel) task

Running "copy:dist" (copy) task
Copied 6 files

Running "copy:es" (copy) task
Copied 6 files

Running "copy:karma" (copy) task
Copied 6 files

Running "karma:watch:run" (karma) task

Running "runKarma:watch:run" (runKarma) task
Running tests in Karma.
PhantomJS 2.1.1 (Windows 8.0.0) ERROR: 'There is no timestamp for /niagara-test-server/karmaUtils.js!'
PhantomJS 2.1.1 (Windows 8.0.0) ERROR: 'There is no timestamp for /niagara-test-server/globals.js!'
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  Error: Script error for "/login/core/auth.min.js"
  https://requirejs.org/docs/errors.html#scripterror
  at http://localhost:9876/__karmanode_modules/requirejs/require.js:143
PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (0.09 secs / 0 secs)
Error running Karma tests: 1`

**Comment by tridium** [comment]
This can happen when running tests while another station is running on your machine.

By default, station output is hidden when running tests because it usually just gets in the way of seeing your test results. But you can enable it by adding the flag --station-log-level=ALL: grunt ci --station-log-level=ALL and you will likely see an error indicating that the web server could not start because another station is holding the port. Stop the other station and your tests should run.
